[package]
name = "beppe_online"
version = "0.1.0"
edition = "2021"
authors = ["Beppe Vanrolleghem beppe.vanrolleghem@gmail.com"]
description = "Testing out wasm"

[lib]
crate-type = ["cdylib"]



[dependencies]
wasm-bindgen = "0.2"
leptos = { version = "0.6.12", features = ["csr"] }

